#!/bin/bash

# Ce fichier fait partie de pdfmm.
# pdfmm est un assistant graphique pour réduire la taille d'un fichier PDF.

# Auteur: Jean-Philippe Fleury <contact@jpfleury.net>
# Copyright © Jean-Philippe Fleury, 2011.

# Ce programme est un logiciel libre; vous pouvez le redistribuer ou le
# modifier suivant les termes de la GNU General Public License telle que
# publiée par la Free Software Foundation: soit la version 3 de cette
# licence, soit (à votre gré) toute version ultérieure.

# Ce programme est distribué dans l'espoir qu'il vous sera utile, mais SANS
# AUCUNE GARANTIE: sans même la garantie implicite de COMMERCIALISABILITÉ
# ni d'ADÉQUATION À UN OBJECTIF PARTICULIER. Consultez la Licence publique
# générale GNU pour plus de détails.

# Vous devriez avoir reçu une copie de la Licence publique générale GNU avec
# ce programme; si ce n'est pas le cas, consultez
# <http://www.gnu.org/licenses/>.

cheminConfig=$HOME/.pdfmm.conf

if [ ! -e $cheminConfig ]; then
	echo "dossier=" > $cheminConfig
fi

if [ -z $(which zenity) ] && [ -z $(which gs) ]; then
	echo "zenity et ghostscript doivent être installés."
	
	exit 1
elif [ -z $(which gs) ]; then
	zenity --error --text="Le paquet «ghostscript» doit être installé."
	
	exit 1
fi

if [ -n "$1" ]; then
	pdfAreduire="$1"
else
	dossier=$(cat $cheminConfig | grep "^dossier=" | cut -d '=' -f 2)
	
	if [ -z "$dossier" ]; then
		dossier=$HOME
	fi
	
	pdfAreduire=$(zenity --file-selection --filename="$dossier/" --title="Sélectionnez un fichier PDF dont la taille doit être réduite")
	
	if [ $? -ne 0 ]; then
		zenity --error --text="Aucun fichier PDF sélectionné."
		
		exit 1
	fi
fi

if [ ! -f "$pdfAreduire" ]; then
	zenity --error --text="Le fichier précisé n'existe pas ou n'est pas utilisable:\n$pdfAreduire"
	
	exit 1
fi

# Mise à jour de la configuration.
dossier=$(dirname "$pdfAreduire")
sed -i "s|^\(dossier=\).*$|\1$dossier|" $cheminConfig

ext="${pdfAreduire##*.}" # Si elle existe, l'extension est récupérée pour conserver sa casse («pdf» ou «PDF»).

if [ "$ext" != "$pdfAreduire" ]; then
	pdfReduit=$(echo "$pdfAreduire" | sed "s/\.$ext$/--.$ext/")
else
	pdfReduit="$pdfAreduire--"
fi

if [ -f "$pdfReduit" ]; then
	zenity --question --text="Le fichier suivant existe déjà:\n$pdfReduit\n\nVoulez-vous vraiment écraser ce fichier?"
	
	if [ $? -eq 1 ]; then
		zenity --info --text="Arrêt du script."
		
		exit 0
	fi
fi

(echo "0"; gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$pdfReduit" "$pdfAreduire") | zenity --progress --pulsate --no-cancel --auto-close --text="$(echo -en "Réduction de la taille du fichier suivant en cours:\n$pdfAreduire")"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
	zenity --error --text="Erreur lors de la réduction de la taille du fichier suivant:\n$pdfAreduire"
	
	if [ -f "$pdfReduit" ]; then
		rm "$pdfReduit"
	fi
	
	exit 1
fi

tailleDepart=$(stat --format=%s "$pdfAreduire")
tailleDepartFormatee=$(ls -hl "$pdfAreduire" | cut -d ' ' -f 5)
tailleSortie=$(stat --format=%s "$pdfReduit")
tailleSortieFormatee=$(ls -hl "$pdfReduit" | cut -d ' ' -f 5)
pourcentageOptimisation=$(echo "(($tailleDepart - $tailleSortie) / $tailleDepart) * 100" | bc -l | cut -d '.' -f 1)

if [ -z $pourcentageOptimisation ] || [ $pourcentageOptimisation == "-" ]; then
	pourcentageOptimisation=0
fi

zenity --info --text="Réduction de la taille du fichier suivant terminée:\n$pdfAreduire\n\nLe nouveau fichier optimisé est:\n$pdfReduit\n\nStatistiques:\n- taille de départ: $tailleDepartFormatee\n- taille de sortie: $tailleSortieFormatee\n- pourcentage d'optimisation: $pourcentageOptimisation%"

exit 0

